### PR TITLE
Feature/list items

### PR DESCRIPTION
**Pull request by troychaplin**
Newly added components:

- Badge
- ListingItems / EventItem
- ListingItems / FeedItem
- ListingItems / FileItem
- LIstingItems / JobItem
- ListingItems / LinkItem
- ListingItems / MarketplaceItem
- ListingItems / NewsItem

There were also several updates to layout components along the way as things came up. Would be good to also have a look over all 4 of the layout components.

Note about badge: how this one is used inside the list components will most likely change, i didn't want to go to far with it yet until we get a better sense of how this will be used and have a few examples of it that we can review and discuss and implement larger changes. So right now it's implemented in a fairly basic way.

Area of concern
On each list item component the Base element uses :any, not sure if this poses any concerns by having it this open. The alternative is to create a new element much like we are doing with the Title element. Would like some feedback on this specific item. Here's an example of the line I am talking about:

`const EventItemBase = ({ as: Component, children, link }: any) => {`

### CODE REVIEW

**Review by Singh-Ish — CHANGES_REQUESTED** [review]
- Where is the folder Coverage coming from? 
- Link will not work with next link (Warning)
- File item the svg should be based on the type of file which is not getting passed from the component (Warning)
- Marketplace image , default fall back image and alt text ?  (recommended )

**Comment by troychaplin** [comment]
@Singh-Ish the coverage folder was added as a part of your commit on October 14 named "updating yarn test" -- https://github.com/cuweb/rds-tailwindui/pull/4/commits/24fe2dc1caff039b377ed1946948f02aed86d33a

**Comment by troychaplin** [comment]
> * Where is the folder Coverage coming from?
> 
>     * Link will not work with next link (Warning)
> 
>     * File item the svg should be based on the type of file which is not getting passed from the component (Warning)
> 
>     * Marketplace image , default fall back image and alt text ?  (recommended )

@Singh-Ish the coverage folder was added as a part of your commit on October 14 named "updating yarn test" -- https://github.com/cuweb/rds-tailwindui/pull/4/commits/24fe2dc1caff039b377ed1946948f02aed86d33a

**Comment by troychaplin** [comment]
SVG icon for files requires discussion, Heroicons does not offer any options for doc types. Font Awesome would be the best option, given we also use their social icons should we just integrate FA alongside Hero, or should we just pick 1 icon package?

**Pull request merged**
